# Generated by Django 3.1.2 on 2020-10-14 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFisrtApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statut',
            options={'managed': False},
        ),
    ]
