# Generated by Django 3.1.2 on 2020-10-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFisrtApp', '0002_auto_20201014_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_column='NOM', max_length=20)),
                ('prenom', models.CharField(db_column='PRENOM', max_length=20)),
                ('mail', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'individu',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='statut',
            table='myFisrtApp_statut',
        ),
    ]
