# Generated by Django 3.1.2 on 2020-10-14 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFisrtApp', '0003_auto_20201014_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statut',
            options={'managed': True},
        ),
    ]
