# Generated by Django 3.1.2 on 2020-10-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFisrtApp', '0004_auto_20201014_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='statut',
            name='commentaire',
            field=models.CharField(default='', max_length=50),
        ),
    ]
