# Generated by Django 3.1.2 on 2020-11-07 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_annuaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('num', models.CharField(choices=[('01', 'étudiant'), ('02', 'enseignant'), ('03', 'apprenant en formation continue')], default='01', max_length=2)),
                ('img', models.ImageField(upload_to='myapp_img/')),
                ('annuaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.annuaire')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.statut')),
            ],
        ),
    ]
