# Generated by Django 3.1.2 on 2020-11-14 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201114_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeIndividu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeGroupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.groupe')),
                ('codeindividu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.individu')),
            ],
        ),
    ]
