# Generated by Django 3.1.2 on 2020-11-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_groupeindividu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='annuaire',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
