# Generated by Django 3.1.2 on 2020-11-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201122_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='statut',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
